### PR TITLE
screen: don't set TERM environment variable and don't merge parent environment

### PR DESCRIPTION
**Pull request by monsta**
Follow-up to https://github.com/mate-desktop/mate-terminal/pull/221, made after suggestion at https://github.com/mate-desktop/mate-terminal/issues/209#issuecomment-363489108.
Fixes https://github.com/mate-desktop/mate-terminal/issues/209 (I hope it does this time).

### CODE REVIEW

**Comment by raveit65** [comment]
Ok, it seems to be working now.
```
[rave@mother ~]$ tr '\0' '\n' < /proc/$(pidof mate-terminal)/environ | grep ^TERM
TERM=dumb
[rave@mother ~]$ printenv | grep ^TERM=
TERM=xterm-256color
[rave@mother ~]$ echo $TERM
xterm-256color
```
And i don't see a regression with a quick test.
But i like to test this a bit more......

**Comment by raveit65** [comment]
After appliying the new env vars this issue is gone, but wordwrap is complete broken
First command is with copying the command in standard terminal size.
Second command is after resizing the terminal.
terminal-bad

**Comment by jmlich** [comment]
I am not sure if I need to compile it in any special way, or install it into OS by "make install" command, or logout and re-login into mate session.
```
git fetch origin pull/231/head:pull231
git checkout pull231
./autogen.sh
./configure
make -j8
src/mate-terminal
```

The version from #231 reports following output (not installed into os, just running src/mate-terminal):
```
[jmlich@pcmlich mate-terminal- (pull231)$  tr '\0' '\n' < /proc/$(pidof mate-terminal)/environ | grep ^TERM
TERM=xterm-256color
[jmlich@pcmlich mate-terminal- (pull231)$ printenv | grep ^TERM=
TERM=xterm
[jmlich@pcmlich mate-terminal- (pull231)$ echo $TERM
xterm
```

I tried also to configure and install in "fedora way"
```
# rpm --eval '%configure'
./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking  --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info
make -j8
sudo make install
```
and run
```
[jmlich@pcmlich ~$ tr '\0' '\n' < /proc/$(pidof mate-terminal)/environ | grep ^TERM
TERM=xterm-256color
[jmlich@pcmlich ~$ printenv | grep ^TERM=
TERM=xterm
[jmlich@pcmlich ~$ echo $TERM
xterm
```

fedora version (mate-terminal-1.19.1-1.fc27.x86_64) outputs the same:
```
[jmlich@pcmlich ~$ tr '\0' '\n' < /proc/$(pidof mate-terminal)/environ | grep ^TERM
TERM=xterm-256color
[jmlich@pcmlich ~$ printenv | grep ^TERM=
TERM=xterm
[jmlich@pcmlich ~$ echo $TERM
xterm
```

I am sorry for late answer. I was ill last week. I have observed the color problem (#209) only on one of my computers. I can access this computer only at Monday. I am not sure if I am doing everything correctly. There could be some cache or something.
I am using system default configuration, except following changes in ~/.bashrc
```
export "QT_LOGGING_RULES=*=true
qt.*=false"

source /usr/share/git-core/contrib/completion/git-prompt.sh
export PS1='[\u@\h \W$(declare -F __git_ps1 &>/dev/null && __git_ps1 " (\[\e[1;31m\]%s\[\e[0m\])")\$ '

export LESS="-R"
export TMOUT=3600 # automatic logout after 1 hour of inactivity
#export TERM=xterm-256color
```
I am overriding TERM variable to workaround #209, but I am disabling that for test.

I have also disabled all my changed in ~/.bashrc and it gives still the same output.

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-terminal/commit/29536a9f07125091f9a06c435b3e9acf42e26968

**Pull request closed without merging**
