### PR TITLE
convert docbook to mallard help docs

### PR DESCRIPTION
**Pull request by yetist**

### CODE REVIEW

**Comment by mbkma** [comment]
Thanks, I agree with you mallard is much more maintainable and readable than docbook.
I have a minor suggestion: With the PR it seems that there is a double frame and the title is missing from the figures:
Screenshot at 2023-01-05 19-30-24
(left: with PR, right: without PR)

**Review by mbkma — APPROVED** [review]
I still approve it, because the documentation is already way more readable than before.

**Comment by yetist** [comment]
Done.

**Review by zhuyaliang — APPROVED** [review]

**Comment by lukefromdc** [comment]
Should we wait for someone on the doc team to review this prior to merge, or merge it now?

**Pull request merged**
