### PR TITLE
Upgrade ui files

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
Seems Ok. Still wondering why the `close` button isn't translated any more in several UIs?
Or is only an update of the transifex resource needed?

**Comment by rbuj** [comment]
> Seems Ok. Still wondering why the `close` button isn't translated any more in several UIs?
> Or is only an update of the transifex resource needed?

I checked that all labels were marked as translatable:
```
$ git grep -F "property name=\"label\"" | grep -v "translatable=\"yes\""
```
To update the translations:
```
$ make -C po mate-terminal.pot
$ make -C po update-po
```

**Comment by rbuj** [comment]
Most po files marked the translation as fuzzy:
```
$ grep -F "\"_Close\"" po/*.po -B 2
```

**Comment by raveit65** [comment]
LOL,
Honestly, i know to update translations ;)
I do that for every new tarball since several  years.

Any way, seems we need a translations update.

**Review by raveit65 — APPROVED** [review]
LGTM

**Pull request merged**
