### PR TITLE
Make dropped tab active

### LINKED ISSUE #152: resizing terminal after drag and drop tabs dont't works propertly
@raveit65 says on:

https://github.com/mate-desktop/mate-terminal/pull/148#issuecomment-258667185

> There is only this little issue with resizing the second terminal from menu left. 
> See https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Test/mate-terminal-resizing.ogv

I can confirm, after drag and drop a tab on a terminal, on the destination, on the menus, **Terminal -> 132x24** and later **80x24** don't works

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39018148-resizing-terminal-after-drag-and-drop-tabs-dont-t-works-propertly?utm_campaign=plugin&utm_content=tracker%2F757836&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F757836&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sc0w**
based on gnome-terminal commit:
https://git.gnome.org/browse/gnome-terminal/commit/?id=abb2018a702adfc57831aea9ebb5c513b9c8bbbd

Fixes #152 

@raveit65 @monsta 

I think now is solved

### CODE REVIEW

**Comment by monsta** [comment]
Not sure if it's the correct way to solve that issue, but it seems to work here.

**Comment by raveit65** [comment]
yeap, that fixes the issue :)
@monsta 
Do you want to fix it in another way?

**Comment by monsta** [comment]
I don't know any other way :smile:

**Comment by monsta** [comment]
Just in case I might be misunderstood - I agree with merging this :smile:

**Comment by raveit65** [comment]
Not sure i we should cherry-pick it to 1.16 ?

**Comment by monsta** [comment]
I'm not sure as well since it's a change in the app behavior...

**Pull request merged**
