### PR TITLE
middle click on a tab: Better behavior

### PR DESCRIPTION
**Pull request by sc0w**
Fixes:

If we are on a tab, and we make middle click on another tab,
it doesn't show the confirm close dialog if there is a foreground process

### CODE REVIEW

**Comment by sc0w** [comment]
The first commit:

Fixes: If we are on a tab, and we make middle click on another tab,
it doesn't show the confirm close dialog if there is a foreground process

but, it creates a new issue: the actual tab position is erroneous

The second commit fixes it

You can test with various tabs, without / with the second commit, and you can see the differences

**Comment by monsta** [comment]
I only tested the first commit so far and haven't found any other issues with tabs... how do I reproduce the wrong position?

**Comment by sc0w** [comment]
@monsta I explain me better with videos:

The first commit makes this new issue, if the destination middle click tab, doesn't have a foreground process:

https://mega.nz/#!kU4xTbDI!jnpm_lGupTD4-f9TIKVzjEJ73sJhIHmCXGuQoNHFsMI

and with all the PR you can verify, it works same than click on X with/without foreground process

**Comment by raveit65** [comment]
Ahh, got it , you replace the title of a tab with numbers.

**Comment by raveit65** [comment]
hmm, i see no different with applying the second commit.
I study you video several times but it seems i don't understand the issue.
@flexiondotorg @XRevan86 @lukefromdc 
Do you understand the issue in the video?

**Comment by sc0w** [comment]
> Ahh, got it , you replace the title of a tab with numbers.

yes, to see what tab was closed

this is the expected, the complete PR:

https://mega.nz/#!ZI4jnKIT!ezUao1IwCMZotW7DZSGECFmpRqFr2vv4wMTZbm3A07I

You can compare with the previous video, the first commit only, and see the differences

If I am on the tab 2, and I close the tab 4, I must stay on the tab 2, this is the expected on all the applications with tabs

I hope everybody can understand me now :)

**Comment by lukefromdc** [comment]
Remember that I do not watch any of the videos on mega due to ad/tracker/js issues

**Comment by raveit65** [comment]
@monsta 
i guess we can merge the PR now?

**Comment by sc0w** [comment]
@raveit65 second commit already renamed

**Comment by monsta** [comment]
Ah... so there's an unwanted tab switching which is fixed in second commit :smile:

**Pull request merged**
