### PR TITLE
screen: stop setting TERM and COLORTERM environment variables

### PR DESCRIPTION
**Pull request by monsta**
closes https://github.com/mate-desktop/mate-terminal/issues/209

taken from:
https://git.gnome.org/browse/gnome-terminal/commit/?id=a0ecd018f070b96a6ca2ff778ddda0f7fde5b847
https://git.gnome.org/browse/gnome-terminal/commit/?id=1d5c1b6ca6373c1301494edbc9e43c3e6a9c9aaf

### CODE REVIEW

**Comment by raveit65** [comment]
Huston, we have a problem.
Since this morning i got this error message with git
```
[rave@mother mate-terminal]$ git log
WARNING: terminal is not fully functional
commit d3f29749a5e2ca5a21f9900717d6c0fc4ace906c (HEAD -> master, origin/master, origin/HEAD)
Author: monsta <monsta@inbox.ru>
Date:   Sat Jan 20 12:05:51 2018 +0300

    screen: stop setting TERM and COLORTERM environment variables
    
    closes https://github.com/mate-desktop/mate-terminal/issues/209
    
    taken from:
    https://git.gnome.org/browse/gnome-terminal/commit/?id=a0ecd018f070b96a6ca2ff778ddda0f7fde5b847
    https://git.gnome.org/browse/gnome-terminal/commit/?id=1d5c1b6ca6373c1301494edbc9e43c3e6a9c9aaf
```
And i don't see any colors anymore for this line
 (HEAD -> master, origin/master, origin/HEAD)

Normally this is colored because gitk is installed 
gitk = Git revision tree visualiser  
from https://git-scm.com/

I need to test is more but it looks like we have a regression.

**Comment by raveit65** [comment]
Hmm, and 'wordwrap' is broken here if you work with long commands from bash history. -_-

**Comment by raveit65** [comment]
One more issue: 
The delete key of my keyboard types '~' in terminal now.

**Comment by raveit65** [comment]
Ok, reverting this commit local fixes all this problems.
Screenshot with PR.
terminal-bad
Screenshot w/o PR
terminal-good
I strongly recommended to revert the commit for the 1.20 release, because it breaks more than it fixes.
Sorry, that i didn't test harder this PR.
@monsta

**Comment by egmontkob** [comment]
What's your `$TERM`?

If it's any different from `xterm-256color` then is it because of a shell startup script mangles it? I'm pretty sure it is. Fix the startup script in that case.

What's the value of `$TERM` if you start the custom command of `printenv` instead of your shell, and keep the terminal open, as per my recent comment at #209?

Do you have the `xterm-256color` terminfo entry installed? What does `tput colors` say?

Does this setting work in other terminal emulators, like `gnome-terminal` or `tilix` and many-many others that have defaulted to `xterm-256color` for many years now?

`gitk` is a graphical app written in Tcl/Tk, I truly doubt it has anything to do with `git` showing colors. I don't have `gitk` installed, and my `git log` is colored.

"it breaks more than it fixes" ... Advertising 256-color support has been the default of plenty of terminal emulators for quite some time now without any significant problem. All the issues were along the lines of `vim` deciding to pick another color scheme and the user liked the previous one better. MATE Terminal is one of the last ones to catch up with advertising 256-color support. You encounter One (1) (!) single issue and suddenly want to retreat because "it breaks more than it fixes", rather than looking at what's broken and how to fix it?? Seriously, please... :)

**Comment by jmlich** [comment]
The commit was removing "xterm" value, not "xterm-256color". 
```
 -	g_hash_table_replace (env_table, g_strdup ("TERM"), g_strdup ("xterm")); /* FIXME configurable later? */ 
```

**Comment by raveit65** [comment]
With commit reverted:
```
[rave@mother ~]$ $TERM
bash: xterm-256color: command not found
```
This is a normal fresh standard fedora installation.

**Comment by egmontkob** [comment]
@jmlich Previously mate-terminal was _overriding_ the value of `TERM` to be `xterm` (the line you quoted). With the removal of that line it no longer _overrides_ `TERM`, so it leaves VTE's default unchanged which has been `TERM=xterm-256color` for 3 years now.

**Comment by egmontkob** [comment]
@raveit65 

"With commit reverted" Do you really mean the commit reverted, or the revert of the commit reverted? For tracking down what's wrong there's not much point in investigating what's working correctly, we'd need to investigate what's _not_ working for you, that is, the current git master of mate-terminal.

"normal fresh standard fedora" - which version?

What does `tput colors` output to you? Also, what do the commands `TERM=xterm tput colors` and `TERM=xterm-256color tput colors` print?

**Comment by raveit65** [comment]
@egmontkob 
As i merged this yesterday to master, "commit reverted" means i don't use this PR.
I am on fedora 26 but let us discuss in bug report.

**Comment by jmlich** [comment]
I haven't mentioned that in #209 explicitly, but the problem came with upgrade from fedora 26 to fedora 27.

**Pull request merged**
