### PR TITLE
profile-editor: properly initialize the first palette color

### PR DESCRIPTION
**Pull request by monsta**
See https://bugzilla.gnome.org/768850 for the bug description and steps to reproduce.

### CODE REVIEW

**Comment by lukefromdc** [comment]
profile_editor_w_pr

**Comment by raveit65** [comment]
I can't reproduce it, merge it if it works for you.

**Comment by monsta** [comment]
@lukefromdc: ah I see... looks like the button has its color set from current GTK+ theme, not the selected color. I'll see if I can find the fix quickly, in this case I might add it to this PR as you suggested.

> the first button of the second row in the palette

But this button seems to have the proper color. You can change to Solarized and back to some other theme to test it.

**Comment by lukefromdc** [comment]
The second row button only shows default grey when opening to "custom" and if it is changed to anything else (automatically) by changing to a built-in theme it will take and hold that theme's color, even with current git master.

**Comment by monsta** [comment]
I don't know... how that second row button should behave?
The color for it is gray in the first three themes, a darker gray/almost black in Rxvt, and dark blue in Solarized...

**Comment by lukefromdc** [comment]
Right now the second row button seems to work OK, with "solarized" coming up as the default palette option. Maybe that one is fixed.  If you look closely at that button in my screenshot, there is not even a border around a color sample as of that time. Now there is and I get a color pulled presumably from solarized there, not sure what else changed.

**Comment by monsta** [comment]
Maybe border just had the same color...?

**Comment by monsta** [comment]
Looking very closely at the screenshot, I see that the button has a gradient, it goes from gray on top to black on down. The button color is dark gray and it's barely visible on that gradient. Looks like it's a bad coincidence of theme colors and button colors.

**Comment by lukefromdc** [comment]
OK, I see and can confirm the grey color sample: 2nd row button is OK. That just leaves the custom mode "Background Color" button, which unlike the second row button looks like this: 

background-color-button

In GtkInspector the "colorswatch" widgets (ALL of them, not just those with issues) come up  as rgb (255,255,255) when not focussed and as something else (same for all colorswatches though) when focussed. Thus GtkInspector is telling us nothing here.

**Comment by monsta** [comment]
It has the background color of the current theme... I don't know why, and I can't always reproduce it. But it's always reproducible with the button for "bold color" to the right of it.

**Comment by monsta** [comment]
Ok, I'll merge it as I couldn't find a quick fix for these button issues, and we need to move on with preparing for 1.20 release.

**Pull request merged**
