### PR TITLE
Use gresources for about_DATA, uimanager_DATA & builder_DATA

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
Just rebased against master to enable travis-ci for this PR.

**Comment by raveit65** [comment]
Oh oh, my terminal looks like this
bildschirmfoto zu 2019-02-22 13-36-57
I think it's better to delay this PR for after 1.22 release.

**Comment by raveit65** [comment]
Sorry, forget what i said.
Now it is OK!
Looks like there was an older mate-terminal process open on my desktop, and starting a new terminal failed because of missing UI files.
....my fault.

**Comment by raveit65** [comment]
As it affects copyright infos in `about` i am not against to merge it before 1.22 release.

**Comment by lukefromdc** [comment]
I figured nothing should be merged now

**Pull request merged**
