### PR TITLE
Add back --geometry positioning support

### PR DESCRIPTION
**Pull request by XRevan86**
I forgot to do it in 0e9e88a.

### CODE REVIEW

**Comment by monsta** [comment]
Just tested it, works great with GTK+ 3.21. :+1: 
Will check with GTK+2 later.

@raveit65 @lukefromdc @sc0w @flexiondotorg 
please test it as well guys.

**Comment by raveit65** [comment]
Works well on top of 1.14.1 release in f24.
Thanks

**Comment by lukefromdc** [comment]
Works fine here with newly-released GTK 3.22. I noticed that --geometry for a terminal is quite different than in a caja window where its in pixels. Matches behavior in terminal configuration GUI, where "80x24" is default and calling "mate-terminal --geometry=160x48" gives double size in both dimensions so this seems to work as intended.

**Comment by monsta** [comment]
Yes, it should be so, it worked like that before. Terminal is resized in rows & columns, not in pixels :smile:

**Comment by lukefromdc** [comment]
Than this seems good to go, guess distros will have to wait for 1.16.1 to
get it?

**Comment by monsta** [comment]
Yes, since 1.16 is released now, we'll put it into 1.16.1. Of course, distro maintainers can pick the patch if they need.

**Comment by raveit65** [comment]
We can't make a new releases after 1 day for one fix, it's better to wait after ubuntu/fedora release to pick up possible other issues if more users use 1.16.0 release.
Also, the geometry option isn't a common usage of mate-terminal.

**Comment by monsta** [comment]
I agree, and I'm not in a hurry for 1.16.1 :smile:

**Comment by lukefromdc** [comment]
No problem either way, it's not something I've ever used.

**Comment by raveit65** [comment]
thank you

**Pull request merged**
