### PR TITLE
allow remapping "search" keyboard shortcuts

### PR DESCRIPTION
**Pull request by sc0w**
Closes https://github.com/mate-desktop/mate-terminal/issues/160

If the issue https://github.com/mate-desktop/mate-terminal/issues/199 is reproducible (only reproducible in some distros), this PR needs the PR https://github.com/mate-desktop/mate-terminal/pull/200 for testing

### CODE REVIEW

**Comment by raveit65** [comment]
@sc0w @monsta 
I hope you agree with me that this is more a new feature as a bug fix.
In result i with do a new 1.18 point release without it.

**Comment by monsta** [comment]
Sure, it's a new feature (with new translatable strings too).

**Comment by sc0w** [comment]
yes, this is for 1.20, and I am working in more improvements...

**Comment by monsta** [comment]
Oops, the key descriptions seem to be copy/pasted from `select-all` key.

**Comment by sc0w** [comment]
@monsta yes, I forgot to edit that, now is fixed

**Comment by raveit65** [comment]
hmm, i have all
terminal-shortcuts
 3 shortcuts in editor.

**Comment by lukefromdc** [comment]
On a further test, I was able to find the dialog in question (it's called from "search" in the menubar) and bring up the strings in dconf-editor, but find-next and find-previous were greyed out in my tests. The overall "find-search" works, but on attempting to change the keyboard shortcut the new one did not work-and ctrl-shift-f continued to work. Not conclusive as I have never used these and am not sure what I am doing, but if someone duplicates this failure to apply a change, more work is needed.

**Comment by sc0w** [comment]
@lukefromdc I think you have the issue https://github.com/mate-desktop/mate-terminal/issues/199 already fixed in master

commit updated with master

@lukefromdc please test again

**Comment by lukefromdc** [comment]
Works fine now: turns out I had only 1/2 of the commit applied, and yes, I had that old issue too. This makes the shortcuts remappable, seems ready to go

**Comment by raveit65** [comment]
merged
https://github.com/mate-desktop/mate-terminal/commit/ca53774e9fcb7ab8fb4402ac09db5ed3f6489c21

**Pull request closed without merging**
