### PR TITLE
terminal-window: expand the content of the comment on about dialog

### PR DESCRIPTION
**Pull request by rbuj**
### Before

Screenshot at 2020-03-30 22-52-14

### After

Screenshot at 2020-03-31 16-39-06

### CODE REVIEW

**Comment by sc0w** [comment]
I don't like the dot in the number version, the look is very weird

according to your concerns, why not add it to **1.24.0.**?

and why not to **MATE Terminal.** ?

**Comment by rbuj** [comment]
@sc0w Generally, a full stop is not used at the end of a title, heading or subheading, as well as in lists or enumerations.

**Comment by sc0w** [comment]
@rbuj 

> Generally, a full stop is not used at the end of a title, heading or subheading, as well as in lists or enumerations.

Generally a full stop is not used un about dialogs, they aren't books.

**Comment by rbuj** [comment]
@selectiveduplicate some examples:
```
$ msgunfmt /usr/share/locale/en_GB/LC_MESSAGES/*.mo | grep -E "[0-9]+\.[0-9]+\."
```
```
"Indicates the version of <GPSInfoIFD>. The version is given as 2.0.0.0. This "
"Indicates the version of <GPSInfoIFD>. The version is given as 2.0.0.0. This "
"deprecated since GNOME 2.12."
"deprecated since GNOME 2.12."
"been deprecated since GNOME 2.12."
"been deprecated since GNOME 2.12."
"deprecated since GNOME 2.12."
"deprecated since GNOME 2.12."
"Window manager to try first. This key has been deprecated since GNOME 2.12."
"Window manager to try first. This key has been deprecated since GNOME 2.12."
"How far you have to move until the stroke input reaches 1.0. This value is "
"How far you have to move until the stroke input reaches 1.0. This value is "
"This defines how long the stroke input stays at 1.0. After that it will "
"This defines how long the stroke input stays at 1.0. After that it will "
```

**Comment by rbuj** [comment]
@sc0w I'm not saying that the full stop should be used for all strings, only that it should be used for the comment. In this case, full stops are needed for ending the two sentences:
```
1st sencence: (It's) A terminal emulator for the MATE desktop.
2nd sencence: (It's) Using VTE 0.60.0.
```

**Comment by selectiveduplicate** [comment]
@rbuj I'd prefer to have the VTE version listed just under the mate-terminal version, as ``VTE 0.60.0``, with no period. But in this way, I'm not sure; it looks weird to me. More reviewers would need to have a look; all the other applications would need changing too after this.

**Comment by rbuj** [comment]
I expanded the comment on about dialog

**Comment by sc0w** [comment]
Personally I prefer to see the dialog simplest, like before, without largest explanations, if we like, we have more info in the help

**Comment by rbuj** [comment]
@vkareh done

Screenshot at 2020-04-01 17-15-15

**Comment by sc0w** [comment]
I am still thinking it is redundant to mention twice `"MATE Terminal"` in the dialog

**Comment by vkareh** [comment]
> I am still thinking it is redundant to mention twice `"MATE Terminal"` in the dialog

It's not mentioning it twice, "MATE Terminal" is the name of the software, and
it happens to be a "terminal" part of the "MATE" desktop environment... I
agree that it's a bit odd, sure, but it's still accurate, in my opinion.

**Comment by raveit65** [comment]
For me this looks OK.
Honestly, i don't care if there is a dot or not, or that mate-terminal is mentioned twice.
I think the world has another problems.
https://www.worldometers.info/coronavirus/

**Comment by sc0w** [comment]
`"MATE Terminal is a terminal ..."` very redundant text :)

anyway I have no problem if others like to merge it

**Pull request merged**
