### PR TITLE
Avoid NULL pointer dereference in terminal_screen_child_exited

### LINKED ISSUE #314: mate-terminal crashes on Fedora
#### Expected behaviour
Not crashing mate-terminal

#### Actual behaviour
Crashes mate-terminal

#### Steps to reproduce the behaviour

     Jia Yuan Lo 2018-11-05 17:14:50 UTC
 
     Description of problem:
     1. Open mate-terminal
     2. Edit -> Profile Preferences
     3. Title and Command
     4. Change When the command exits: "Exit the terminal" to "Hold the terminal open"
     5. Close editing profile window
     6. Close mate-terminal
     7. Crash

     Ben Greear 2018-12-14 18:36:00 UTC
 
     Similar problem has been detected:
 
     I was closing a mate terminal window and then it crashed,
     and of course brought down all 20 or 30 terminals I had open on multiple desktops
     and all the applications I had opened through them!
 

     Ben Greear 2018-12-14 19:06:37 UTC
 
     I am thinking a partial work-round might be the mate-terminal --disable-factory option
 
     That way, at least only one window should crash at a time.

     Bernd Schemmer 2019-12-10 09:28:52 UTC
 
     Description of problem:
     opened a ssh session via Launcher on the MATE Desktop using the command:
 
     /usr/bin/mate-terminal  --profile="LNX installserver2" --disable-factory
 
     Everything is fine ; the session works. But closing the session using the Close button
     of the window always crashes the mate-terminal process
 
     Without the parameter "--disable-factory" for the mate-terminal all other instances
     of mate-terminal wiill also crash.
 
     The error only occurs for Fedora running in a VirtualBox machines . It's reproducable
     in two Virtual Box machines. 
     The error is there since a long time now - installing the current patches for Fedora
     many times in the last month
     did not fix that bug yet. The last "yum update" was done today - also without fixing
     the bug.
 
     The error does not happen in Fedora installed on bare metal (Thinkpad T540p)

#### MATE general version
1.20.1-2

#### Package version
1.20.1-2

#### Linux Distribution
Fedora 30
Fedora 31

#### Link to downstream report of your Distribution
https://bugzilla.redhat.com/show_bug.cgi?id=1781564

### PR DESCRIPTION
**Pull request by rbuj**
Fixes #314

### CODE REVIEW

**Comment by sc0w** [comment]
I see this warning in terminal when closing mate-terminal windows (running mate-terminal in xterm)

`** (mate-terminal:45473): CRITICAL **: 01:32:55.425: terminal_window_remove_screen: assertion 'gtk_widget_get_toplevel (GTK_WIDGET (screen)) == GTK_WIDGET (window)' failed`

@rbuj maybe you know how to fix it?

but it isn't related to this PR, I see the same warning with mate-terminal 1.22.1

This PR fixes the issue, and I see no new warnings in travis logs.

**Comment by rbuj** [comment]
@cwendling You can't either do it before.
```C
#include <stdio.h>
#include <signal.h>

int main(void)
{
  char c;

  raise(9);
  c = getchar();
  return 0;
}
```
The breakpoint on [terminal-screen.c:1941](https://github.com/mate-desktop/mate-terminal/blob/master/src/terminal-screen.c#L1941) is not reached.

Captura de pantalla a 2019-12-12 12-49-49

Test:
```shell
$ gcc test.c -o test
$ /usr/bin/mate-terminal -- /home/robert/Devel/test
```

**Comment by cwendling** [comment]
@rbuj well, it works for me (OK, I'm using 1.22.1 just now, but I could test on master if need be):
Capture

Are you sure your breakpoint works?  [`_terminal_debug_print()`](https://github.com/mate-desktop/mate-terminal/blob/master/src/terminal-debug.h#L57) is a macro that expands to a test; I wouldn't be sure on what the breakpoint is actually set.

**Comment by cwendling** [comment]
@rbuj BTW adding the `getchar()` call in the test program should never be reached as the program received SIGKILL already.

**Comment by rbuj** [comment]
Ok, I was wrong. I didn't debug it correctly.
Captura de pantalla a 2019-12-12 14-33-39

**Comment by rbuj** [comment]
Please, check if this new approach is valid. The command executed by the terminal, it's stored in `priv->override_command`, so let's check if it's NULL. in such case we can safely close the window.

**Comment by lukefromdc** [comment]
I can confirm the terminal_window_remove_screen warning also exists with master

**Comment by raveit65** [comment]
With updated PR the terminal or any other terminal windows don't crash  if closing one.
But executing `exit` in terminal closes the terminal now.
I don't use `TERMINAL_EXIT_HOLD` normally, but is this the right behaviour now?

**Comment by rbuj** [comment]
I'm sorry, I think it's fixed now.

**Comment by sc0w** [comment]
I still vote to keep original change, it was working like a charm :)

**Comment by rbuj** [comment]
@sc0w There are segfaults with the initial PR:
```shell
$ mate-terminal -- exit
$ mate-terminal -- /usr/bin/sh -c 'kill -9 \$PPID'
```

Initial PR:
```shell
$ git diff master src/terminal-screen.c
```
```patch
diff --git a/src/terminal-screen.c b/src/terminal-screen.c
index aba6cb1..936c81a 100644
--- a/src/terminal-screen.c
+++ b/src/terminal-screen.c
@@ -1956,6 +1956,12 @@ terminal_screen_child_exited (VteTerminal *terminal, int status)
                break;
        case TERMINAL_EXIT_HOLD:
        {
+               if (status == 9)
+               {
+                       g_signal_emit (screen, signals[CLOSE_SCREEN], 0);
+                       break;
+               }
+
                GtkWidget *info_bar;
 
                info_bar = terminal_info_bar_new (GTK_MESSAGE_INFO,
```
Test script:
```shell
#!/bin/bash
mate-terminal -- /usr/bin/bash -c 'exit'
mate-terminal -- /usr/bin/bash
mate-terminal -- /usr/bin/ls
mate-terminal -- /usr/bin/bash -c 'sleep 100 & killall -9 sleep'
mate-terminal
# failed tests:
#mate-terminal -- exit
#mate-terminal -- /usr/bin/sh -c 'kill -9 \$PPID'
```
I just created the unit tests with your comments.

**Comment by rbuj** [comment]
The 2nd approach:
```shell
[robert@localhost mate-terminal]$ git diff master src/terminal-screen.c
```
```patch
diff --git a/src/terminal-screen.c b/src/terminal-screen.c
index aba6cb1..cdd38bc 100644
--- a/src/terminal-screen.c
+++ b/src/terminal-screen.c
@@ -1952,10 +1952,14 @@ terminal_screen_child_exited (VteTerminal *terminal, int status)
                g_signal_emit (screen, signals[CLOSE_SCREEN], 0);
                break;
        case TERMINAL_EXIT_RESTART:
-               terminal_screen_launch_child_on_idle (screen);
+               if (priv->override_command != NULL)
+                       terminal_screen_launch_child_on_idle (screen);
                break;
        case TERMINAL_EXIT_HOLD:
        {
+               if (priv->override_command == NULL)
+                       break;
+
                GtkWidget *info_bar;
 
                info_bar = terminal_info_bar_new (GTK_MESSAGE_INFO,
```
Test:
```shell
#!/bin/bash
mate-terminal --title "Test 1" -- /usr/bin/bash -c 'exit'
# Segfault on closing "Test 2" window
#mate-terminal --title "Test 2" -- /usr/bin/bash
mate-terminal --title "Test 3" -- /usr/bin/ls
mate-terminal --title "Test 4" -- /usr/bin/bash -c 'sleep 100 & killall -9 sleep'
mate-terminal --title "Test 5"
#mate-terminal --title "Test 6" -- exit
#mate-terminal --title "Test 7" -- /usr/bin/sh -c 'kill -9 $PPID'
mate-terminal --title "Test 8" & kill -9 $!
mate-terminal --title "Test 9" -- /usr/bin/bash & kill -9 $!
exit
echo "hello world!"
```

**Comment by raveit65** [comment]
With first approach and `mate-terminal -- /usr/bin/sh -c 'kill -9 \$PPID'`
```
/usr/bin/sh: line 0: kill: $PPID: arguments must be process or job IDs
```
And I can confirm that `mate-terminal -- exit` close all terminal.
Are those really errors or segfaults?

The problem with second approach is that it isn't the expected behaviour when someone chose `Hold terminal open when command exit (finished)`.
User expect that terminal keeps open, or not?

**Comment by rbuj** [comment]
Typing exit on the terminal shows also the relaunch button:
```patch
index aba6cb1..94105af 100644
--- a/src/terminal-screen.c
+++ b/src/terminal-screen.c
@@ -1956,6 +1956,12 @@ terminal_screen_child_exited (VteTerminal *terminal, int status)
                break;
        case TERMINAL_EXIT_HOLD:
        {
+               if ((status == 9) && (priv->override_command == NULL))
+               {
+                       g_signal_emit (screen, signals[CLOSE_SCREEN], 0);
+                       break;
+               }
+
                GtkWidget *info_bar;
 
                info_bar = terminal_info_bar_new (GTK_MESSAGE_INFO,
```
Test
```shell
#!/bin/bash
mate-terminal --title "Test 1" -- /usr/bin/bash -c 'exit'
# SEGFAULT ON CLOSING TEST 2 WINDOW mate-terminal --title "Test 2" -- /usr/bin/bash
mate-terminal --title "Test 3" -- /usr/bin/ls
mate-terminal --title "Test 4" -- /usr/bin/bash -c 'sleep 100 & killall -9 sleep'
mate-terminal --title "Test 5"
# SEGFAULT mate-terminal --title "Test 6" -- exit
# SEGFAULT mate-terminal --title "Test 7" -- /usr/bin/sh -c 'kill -9 $PPID'
mate-terminal --title "Test 8" & kill -9 $!
mate-terminal --title "Test 9" -- /usr/bin/bash & kill -9 $!
gcc -x c -o test - <<EOF
#include <stdio.h>
#include <signal.h>

int main(void)
{
  char c;

  raise(9);
  c = getchar();
  return 0;
}
EOF
mate-terminal --title "Test 10" -- ./test
./test
exit
echo "hello world!"
```

**Comment by rbuj** [comment]
master:
```
# SEGFAULT ON CLOSING TEST 5 WINDOW
mate-terminal --title "Test 5"
```

**Comment by raveit65** [comment]
@cwendling 
Do you like to approve?

**Pull request merged**
