### PR TITLE
avoid deprecated vte_terminal_search_get_gregex

### PR DESCRIPTION
**Pull request by sc0w**
Fixes https://github.com/mate-desktop/mate-terminal/issues/199

### CODE REVIEW

**Comment by raveit65** [comment]
@monsta 
This blocks a new 1.18.x release for me, please test.

**Comment by raveit65** [comment]
For the record, i am fine with vte required version bump for the distros where i build packages.

**Comment by monsta** [comment]
I'll check it, but is it ok to bump VTE requirement to 0.46 for all supported distros?

**Comment by monsta** [comment]
Answering my own question: not ok for current Mint releases. Need to add `VTE_CHECK_VERSION` for these.

**Comment by sc0w** [comment]
@monsta ok, done!

**Comment by monsta** [comment]
Thanks 🙂

**Pull request merged**
