### PR TITLE
terminal-window: replace deprecated gtk_menu_popup

### PR DESCRIPTION
**Pull request by raveit65**
Please test.

### CODE REVIEW

**Comment by lukefromdc** [comment]
Most likely the use of NULL (which uses the default trigger_event ) is bringing in the wrong event. To fix this would require passing the button press event to notebook_popup_menu_cb , which does not already receive the event. I tested using 
`  gtk_menu_popup_at_pointer (GTK_MENU (menu), (const GdkEvent*) event);`
in notebook_button_press_cb, which already receives an event passed to it but it had no effect, so the problem is in notebook_popup_menu_cb, which does not have an event passed to it and worse, I did not find a simply way to pass this to it.

**Comment by vkareh** [comment]
@lukefromdc - yeah the `"show-popup-menu"` is a custom event and it passes a `TerminalScreenPopupInfo` object, but there are two calls to it:
* https://github.com/mate-desktop/mate-terminal/blob/ebaf49bf223109385f05eaf0717efc688890f2e8/src/terminal-screen.c#L1665
* https://github.com/mate-desktop/mate-terminal/blob/ebaf49bf223109385f05eaf0717efc688890f2e8/src/terminal-screen.c#L1722

One has access to the event, the other one doesn't. I actually got the warning twice on every click up until I opened a new terminal tab, then it stopped the warning. I wonder if once of those emits is unnecessary/redundant?

**Comment by raveit65** [comment]
Yes, i can confirm the twice warnings.
I think i will split commit in two for the moment.

**Comment by raveit65** [comment]
Why `notebook_popup_menu_cb` ?
The warning is caused by `popup_clipboard_targets_received_cb` function.
I do not really know which menu is triggered by `gtk_menu_popup_at_widget` in `notebook_popup_menu_cb`, but this isn't the code block which causes the warning.

**Comment by sc0w** [comment]
seems that warning comes from here:

https://gitlab.gnome.org/GNOME/gtk/blob/3.22.30/gdk/gdkevents.c#L2417

**Comment by sc0w** [comment]
@raveit65 please test https://github.com/mate-desktop/mate-terminal/commit/1352686f1e53ea1ec568dbfa73b1ee4535f64545

and feel free to cherry-pick here if it works for you

**Comment by raveit65** [comment]
@sc0w 
Thanks a lot , this fixes the warning.
@lukefromdc @vkareh 
Can you review again please?

**Comment by lukefromdc** [comment]
Here's my analysis of memory management in this PR, hope I am correct:

GdkEvent *event is freed in the end of the function.
GdkDevice *device is not to be freed as according to
https://developer.gnome.org/gdk3/stable/GdkSeat.html
gdk_seat_get_pointer() returns  "a master GdkDevice with pointer capabilities. This object is owned by GTK+ and must not be freed."
For 
GdkSeat *seat
similar uses of  gdk_display_get_default_seat in Nautilus are not explicitly freed in the functions it
is called from, implying that this is again returning a pointer to memory owned by something
else that must not be freed

So we are looking good to go on memory management unless I am wrong somewhere

**Comment by vkareh** [comment]
@raveit65 - do you want to squash the first 3 commits, or should we rebase and merge like this?

**Comment by raveit65** [comment]
All done :)

**Pull request merged**
