### PR TITLE
Removed line to explicitly set xterm as TERM type

### PR DESCRIPTION
**Pull request by Toothless204**

### CODE REVIEW

**Comment by raveit65** [comment]
Why you want to commit this?

**Comment by Toothless204** [comment]
There has been a long standing issue about mate-terminal only showing 8 colors

See here: https://github.com/mate-desktop/mate-terminal/issues/209

**Comment by raveit65** [comment]
And this fixes the issue?

**Comment by Toothless204** [comment]
Indeed it does break line-wrapping I will look and see if I can fix that too

thanks for pointing that out, I hadn't seen that other issue

**Comment by Toothless204** [comment]
Fixed it, it no longer appears to break line-wrapping, could you just check to make sure?

Thanks

**Comment by raveit65** [comment]
I see no change in your commit?

**Comment by Toothless204** [comment]
Yeah, I did some further testing to make sure and I found it works fine

Could you check to make sure?

**Comment by raveit65** [comment]
No, same like what i wrote here.
https://github.com/mate-desktop/mate-terminal/pull/231#issuecomment-366522455
1. Open terminal with standard size.
2. Copy a long command from clipboard to terminal, e.g
```tr '\0' '\n' < /proc/$(pidof mate-terminal)/environ | grep ^TERM```
And command line looks like the screenshot in link with broken line wrap.
This happens always if the command is longer than terminal wide.

And another issue which is fixed by second commit in other PR.
```
[rave@satellite mate-terminal]$ git log
WARNING: terminal is not fully functional
-  (press RETURN)

```

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-terminal/commit/29536a9f07125091f9a06c435b3e9acf42e26968

**Pull request closed without merging**
