### PR TITLE
runtime warnings

### PR DESCRIPTION
**Pull request by raveit65**

### CODE REVIEW

**Comment by monsta** [comment]
I wonder why there's a warning when ```gtk_window_set_transient_for``` is already called in the code (without this PR I mean)... @XRevan86: maybe you know?

**Comment by monsta** [comment]
Weird, keyboard shortcuts dialog and encodings dialog also have that transient thing set, but they don't generate any warnings.

**Comment by raveit65** [comment]
should i merge or delete the PR?

**Comment by monsta** [comment]
Don't merge yet, I accidentally found an alternative solution: https://github.com/mate-desktop/mate-terminal/pull/167. It works for me with GTK+ 3.22, but a bit more testing won't hurt.

**Comment by raveit65** [comment]
> Don't merge yet, I accidentally found an alternative solution: #167. It works for me with GTK+ 3.22, but a bit more testing won't hurt.

I am still wondering why you had the time or what the motivation is to do the same :-)
I see only in comments that you don't like it but no real reason to do it in another way than upstream.
But in this case i am passionless as i don't spend much time to adopt the commits from upstream.

**Pull request closed without merging**
