### PR TITLE
terminal-screen: avoid deprecated 'vte_terminal_spawn_sync'

### PR DESCRIPTION
**Pull request by sc0w**

### CODE REVIEW

**Comment by lukefromdc** [comment]
How do I test this?

**Comment by sc0w** [comment]
@lukefromdc  for example, you can test if you see the dialog to confirm close tabs if there is a foreground process, and if you don't see the dialog if there is no foreground process, the same behavior as before

**Comment by monsta** [comment]
Hey. This is not buildable in Debian Stretch with VTE 0.46.1.

**Comment by sc0w** [comment]
@monsta it was merged only to master branch.

**Comment by monsta** [comment]
That's what I use daily in my Stretch-based system.

**Pull request merged**
