### PR TITLE
support gnome-wayland session

### PR DESCRIPTION
**Pull request by raveit65**

### CODE REVIEW

**Comment by raveit65** [comment]
I guess this will not work with weston compositor but fixes mate-terminal in gnome-wayland session, just tested with f26.
downstream report:
https://bugzilla.redhat.com/show_bug.cgi?id=1411035

**Comment by raveit65** [comment]
@lukefromdc
Please test is as you have weston installed.

**Comment by lukefromdc** [comment]
Works fine in Weston session

**Comment by raveit65** [comment]
Cool, so this simple fix is OK in general for Weston.
Than i will merge this for other packages too.

**Comment by raveit65** [comment]
I wouldn't do a PR if this isn't enough for getting m-t working with gnome-wayland. ;-)

**Comment by monsta** [comment]
I thought that commit was enough to fix the crash... was there something else besides the crash?

**Pull request merged**
