### PR TITLE
typo: archvio -> archivo

### PR DESCRIPTION
**Pull request by sc0w**

### CODE REVIEW

**Comment by monsta** [comment]
Translations are maintained on Transifex, so it should be corrected there.

https://www.transifex.com/mate/MATE/mate-terminal/

**Comment by sc0w** [comment]
@monsta Forbidden access in that page for me

**Comment by monsta** [comment]
Yes, you need to ask someone from translation team for that language, or ask to join the team and then correct the typo.

**Comment by sc0w** [comment]
done!

**Pull request closed without merging**
