### PR TITLE
Explicitly enable bright bold to match new VTE versions

### LINKED ISSUE #278: VTE 0.56 breaks bold colors
In VTE 0.56 the widget option to use bright colors for bold text was changed from enabled by default to disabled by default, and renamed from `no_bold_is_bright` to `bold_is_bright` (i.e. it must now be explicitly enabled). MATE terminal does not use this option therefore a lot of applications that use bold/bright text are now broken (including `ls` and `cmake`).

### PR DESCRIPTION
**Pull request by micheal65536**
Fixes #278

### CODE REVIEW

**Comment by sc0w** [comment]
NOTE:  the function `vte_terminal_set_bold_is_bright` works since `VTE 0.52` and mate-terminal requires `0.48`

@micheal65536 I think that line requires `#if VTE_CHECK_VERSION (0, 52, 0)`

**Comment by micheal65536** [comment]
@sc0w Thanks for pointing this out. I meant to say that it requires at least VTE 0.52 but I forgot. Also wasn't sure what version MATE terminal officially requires, if upgrading the required version is acceptable, or how to conditionally check the version.

I will add the version check macro as soon as I get a chance.

**Comment by micheal65536** [comment]
@lukefromdc Yes, the function/option was present since version 0.52 (and the GNOME developers did tell other projects about it at the time) but in 0.56 the default was changed from true to false without any warning.

**Comment by micheal65536** [comment]
I've added the version check macro as requested. I haven't tested if this builds with either newer or older versions of VTE.

**Comment by sc0w** [comment]
@micheal65536 thanks!

**Pull request merged**
