### PR TITLE
require GTK+ >= 3.14, drop GTK+2 code and --with-gtk build option

### PR DESCRIPTION
**Pull request by monsta**
@flexiondotorg @clefebvre @raveit65 @posophe @XRevan86 @willysr @obache @NP-Hardass

Next one... now we move mate-terminal to GTK+3:

- minimum GTK+ version is set to 3.14
- GTK+2 code is dropped (still need to fix deprecations in GTK+3 code though)
- old VTE code is dropped too - we support only VTE >= 0.38, with VTE API 2.91
- ```--with-gtk``` build option is dropped as well
- build-deps on GTK+ and VTE dev packages are changed (that's what you need to do in your distros)

For example, in Debian/Ubuntu build-deps are changed as follows:
```libgtk2.0-dev -> libgtk-3-dev```
```libvte-dev -> libvte-2.91-dev```

Also this PR makes mate-terminal independent of libmate-desktop (or else we couldn't move it to GTK+3 alone), so you can drop build-dep on it as well. However, it was achieved at the cost of introducing build-dep on libdconf, so you should add it.

Please note that **runtime** dependencies on schemas from mate-desktop (```org.mate.interface```) and gnome (```org.gnome.system.proxy```) are still needed.

### CODE REVIEW

**Comment by raveit65** [comment]
Do i need this runtime requires to mate-desktop?

# needed to get a gsettings schema, rhbz #908105
Requires:      mate-desktop-libs
Requires:      gsettings-desktop-schemas

I know gsettings-desktop-schemas from gnome is needed.

**Comment by raveit65** [comment]
ok, got it,
runtime requires to mate-desktop gsettings and gnome schemas  are needed, see mentioned rhbz report.

**Comment by raveit65** [comment]
I just switched to gtk3 for upcoming f24 :wink:

**Comment by monsta** [comment]
Yes, forgot to mention that runtime deps on schemas are still needed, thanks. I've updated the first post.

**Comment by monsta** [comment]
@flexiondotorg @clefebvre oops, runtime dep on ```gsettings-desktop-schemas``` was missing in our debs, so I've added it in https://github.com/mate-desktop/debian-packages/commit/b8f2d0b9a0aa5322d6f5af54dc9ebe7b4f462e5e

**Pull request merged**
