### PR TITLE
terminal-window: Fix: Session dbus daemon saturated

### PR DESCRIPTION
**Pull request by sc0w**
Fixes https://github.com/mate-desktop/mate-terminal/issues/233

In the tests, make sure the commits https://github.com/mate-desktop/mate-terminal/commit/294ce367b2d376bb4b53017136c82af94a15026e https://github.com/mate-desktop/mate-terminal/commit/7ebc9d18b3abd2d1f3baa3a8e80b1fd9cb6e0621 are working

### CODE REVIEW

**Comment by lukefromdc** [comment]
I do not know the symptoms of the issue and use the terminal all the time without any visible symptoms. What should I be looking for?

**Comment by cryobry** [comment]
@lukefromdc 

See: https://github.com/mate-desktop/mate-terminal/issues/233#issuecomment-394199432

**Comment by sc0w** [comment]
@lukefromdc you can see the previous comment, and you can see exactly the number of the key press event with `gtk-inspector`, and see `journalctl -f`

**Comment by raveit65** [comment]
I can reproduce the issue here, doesn't matter if thos gsettings keys are enabled or not.
Now testing PR.

**Comment by thanks4opensource** [comment]
Sorry for the necro-post, but I'm trying to see if this horrible bug really got fixed and if so, in what release.

I can confirm the bug is still there in 1.20.0 (which is what the distro I'm using has) , and although my GitHub-fu isn't the best, I think the patch mentioned above is included in that branch. I will try to build and test master, but any further information about the timeline would be appreciated.

To expand on the methods to see the bug that others have posted here and in #233, a very easy way is to run `dbus-monitor` in a shell window. On each  and every keypress, in any mate-terminal, you'll see something like:
`method call time=1578593980.211454 sender=:1.11 -> destination=org.freedesktop.DBus serial=5229 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',interface='ca.desrt.dconf.Writer',path='/ca/desrt/dconf/Writer/user',arg0path='/org/mate/terminal/global/'"
method return time=1578593980.211487 sender=org.freedesktop.DBus -> destination=:1.11 serial=5200 reply_serial=5229
`

Note that the `serial` and `reply_serial` both increment with each keypress. It is only when they exceed the default 50000 limit that journalctl or other logging system starts overflowing on every keypress with messages like:
`Jan 08 14:06:09 hostname dbus-daemon[2147]: [session uid=500 pid=2147] Connection ":1.14" is not allowed to add more match rules (increase limits in configuration file if required; max_match_rules_per_connection=50000)
`

Logging out of the desktop session and back in resets the `serial` and `reply_serial` counters in the dbus session, so I assume that the reason others haven't seen the problem is that they don't type 50,000 mate-terminal keypresses before doing so. I leave my machines up, with the desktop session open (FVWM, but I don't think that affects the problem), for months at a time. I typically hit the limit within a few days.

IMO, regardless of whether the limit is hit and journalctl gets bombarded, this is a horrible, show-stopping bug. The performance implications, if not also security ones, of sending each keystroke through D-Bus are significant. Mate-terminal has been my go-to terminal emulator of choice for many years, but if this can't be fixed (possibly by me) I'll have to go to something else.

Thanks in advance for any interest in this problem.

**Comment by cryobry** [comment]
@thanks4opensource I'm using 1.22.1 and cannot repro, so perhaps you should just update your version of mate-terminal.

**Comment by thanks4opensource** [comment]
Thanks for the quick response, @cryobry, and for the confirmation  that 1.20.0 doesn't have the patch. 

As a quick test I found a pre-built RPM with 1.23.0 and extracted just the usr/bin/mate-terminal it contained. It still showed the same problems, but I also had 1.20.0 versions running, and `ps` always  shows just one mate-terminal process, so maybe 1.23.0 attached to that. (I don't understand the architecture, but seems possible that a single mate-terminal binary is running all visible mate-terminal windows.)

I'll try to build master and/or 1.22 from source and check that, plus maybe the RPM 1.23.0,  without any 1.22.0 running and report back what I find.

Thanks again.

**Comment by thanks4opensource** [comment]
Sorry for more problems/questions, but ...

I tried to build mate-terminal from the master branch, after first installing the mate-common package for my distro. Then found that yelp-build is also required. (It would be nice if autogen.sh reported both missing dependencies instead of exiting on the first one.)

I'll go down the road of getting all the dependencies (likely more will be required during autogen/configure/make), but first I tried again running the 1.23.0 binary I got from the RPM. I confirmed that running 1.23.0 when 1.20.0 mate-terminals are active in fact does just open another 1.20.0 (confirmed via Help -> About). So I closed all running 1.20.0 terminals and then ran 1.23.0. That resulted in:
```
$ mate-terminal
(mate-terminal:19844): GLib-GIO-ERROR **: Settings schema 'org.mate.terminal.profile' does not contain a key named 'use-urls'
[1]    19844 trace trap (core dumped)  mate-terminal
```

I confirmed, and then tried to fix, this via:

```
$ dconf dump /org/mate/terminal/profile/
$
$ dconf write /org/mate/terminal/profile/profile/use-urls false
$ dconf dump /org/mate/terminal/profile/
[profile]
use-urls=false
$
```
but got the same Glib error and coredump as before.

Am I doing something wrong? Will I get the same error if and when I succeed in building mate-terminal from source? I mentioned before that I'm running under FVWM and didn't think that was a problem as I've been doing so for years. Has something changed and mate-terminal will now only run with the full MATE desktop? If so, I understand (that's the intended use for the code) but it would be a shame as mate-terminal is IMO the best terminal application available.

Thanks again for any advice.

**Comment by cryobry** [comment]
This is not a mate-terminal problem, it's a packaging problem for your
distro's support channels. I'd be highly suspect of any distribution that
ships such old software without a mechanism to install newer versions via
the package manager. Regardless, building from source should be trivial,
perhaps you should use a container or VM for your build environment if you
do not wish to install build dependencies on your host.

**Comment by thanks4opensource** [comment]
I'm using openSUSE Leap 15.1 and I've never had any problems with the openSUSE YaST (GUI)  and zypper (commandline) package system. (They generally release several dozen package upgrades a week which always install without incident.) I don't know why they're stuck back on such an old mate-terminal version, in in fact if and when I get this sorted out I plan to post a request on their support website that they upgrade their version.

When you say "This is not a mate-terminal problem" are you referring to my needing to install extra packages to build the source, or to the missing dconf key value? I don't mind installing extra packages to build things, it's just time consuming. Is there some package outside those required to compile from source that will provide missing key/value pair? Why did setting it with dconf fail? Again, openSUSE is pretty good at managing package dependencies, but if I'm jumping mate-terminal ahead of their version my runtime environment could have the same problem after I get the source built.

**Comment by cryobry** [comment]
You can follow the directions to install the updated mate repo for OS Leap
15.1 here: https://en.opensuse.org/Portal:MATE

**Comment by thanks4opensource** [comment]
Thanks, @cryobry! I updated my mate-terminal (and the matching mate-terminal-lang) with the 1.22.1 versions from that repository and they work perfectly. Nothing in dbus-monitor so I'm sure nothing will hit journalctl either. All good!

I don't understand the openSUSE policies for what gets updated in the stable "Leap" releases (there's also the rolling release Tumpleweed version, but I've tried that and had problems with it). As I said, I get very frequent updates on Leap from the standard repositories, but maybe this wasn't considered important enough to change in the stable series. On the other hand, 15.1 was first released in May 2019 which is after the date of this 1.20.1 patch, so I don't know why they chose 1.20.0 in the first place (and never changed). Maybe it was past their beta verification cutoff?

In any case, "all's well that ends well". I already posted on the openSUSE forums, so I'll close that out with a reiterated request to make sure 1.22 or later gets into the upcoming Leap 15.2. Once again, thanks -- I spend most of my waking hours typing into mate-terminal (dozens of them open on my desktop at once) and getting this fixed is a great help.

**Pull request merged**
