### PR TITLE
terminal_profile_edit_dialog_page_scroll_event_cb is only used in profile-editor.c

### PR DESCRIPTION
**Pull request by rbuj**
Based on:
- https://github.com/mate-desktop/mate-terminal/commit/8d2eb0898154f2624e2ae34039169f307a3411a5
- https://github.com/mate-desktop/mate-terminal/commit/622e2d1272bf2d7a99d147482ae6a51b0a77f188

### CODE REVIEW

**Comment by tamplan** [comment]
Well done, more the function is static!
My C and my English are a rusty fear...

**Comment by tamplan** [comment]
You rename the function?
I have understood the functions' name should be begins the same way, in this case `terminal_`.

Is there any rule about this? In case i make mistakes later...

**Comment by rbuj** [comment]
`profile_editor_nb_scroll_event_cb ` is used only in `profile-editor.c`, it's different to `terminal_profile_edit` which is a global function.

doxy

**Comment by tamplan** [comment]
Ok, if a function is global (ie called more than once and no static), this name should begin with other like the filename?
Private functions can be names like we want because they are private (with a correct name i presume)?

Good method, i note it.

What is the tool you use for this diagram?

I know every day i have more and more things to learn...

**Comment by rbuj** [comment]
> What is the tool you use for this diagram?

[doxygen](https://www.doxygen.nl/index.html)

**Comment by tamplan** [comment]
> > What is the tool you use for this diagram?
> 
> [doxygen](https://www.doxygen.nl/index.html)

Ok, thanks you.

**Pull request merged**
