### PR TITLE
terminal-window: "utilities-terminal" icon with "Open Terminal"

### PR DESCRIPTION
**Pull request by sc0w**
Before:

Later:

Before:

Later:

### CODE REVIEW

**Comment by sc0w** [comment]
@rbuj yes, done

**Comment by yetist** [comment]
build and run well.
There are some menu items on the pop-up menu that have no icons. Can you add them?

**Comment by raveit65** [comment]
@sc0w 
Do you plan to extend the PR or can this be merged?

**Comment by sc0w** [comment]
I will open new PR with missing icons in popup menu

**Pull request merged**
